default:
  # install required packages, use another user but root (so permission unit tests work fine) and setup right permissions to the new user for compiling
  before_script: 
    - apt-get update  && apt-get install -y libfontconfig1 && useradd -m testuser && exec su testuser -c bash  

stages:
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"

linux-java-8:
  image: maven:3.9-amazoncorretto-8-debian
  stage: test
  script: 
    - mvn $MAVEN_CLI_OPTS test

linux-java-11:
  image: maven:3.9.5-amazoncorretto-11-debian
  stage: test
  script: 
    - mvn $MAVEN_CLI_OPTS test

linux-java-17:
  image: maven:3.9.5-amazoncorretto-17-debian
  stage: test
  script: 
    - mvn $MAVEN_CLI_OPTS test

linux-java-21:
  image: maven:3.9.5-amazoncorretto-21-debian
  stage: test
  script: 
    - mvn $MAVEN_CLI_OPTS test
