image:
  name: maven:3.9.5-amazoncorretto-21-debian
  entrypoint: ['bash', '-c', 'useradd testuser && exec su testuser -c bash']  # use another user but root, so unit tests work fine with permissions checks

stages:
  - compile
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - ~/.m2/repository/
    - ~/target/

compile:
  stage: compile
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test



