image:
  name: maven:3.9.5-amazoncorretto-21-debian
  entrypoint: ['bash', '-c', 'apt-get install -y fontconfig && useradd -m testuser && chown -R testuser /builds && exec su testuser -c bash']  # install required packages, use another user but root (so permission unit tests work fine) and setup right permissions to the new user for compiling

stages:
  - compile
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"

compile:
  stage: compile
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test



