default:
  # install required packages, use another user but root (so permission unit tests work fine) and setup right permissions to the new user for compiling
  before_script: 
    - apt-get update  && apt-get install -y libfontconfig1
    - useradd -m testuser
    - exec su testuser -c bash  

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"

java-8-linux:
  image: maven:3.9-amazoncorretto-8-debian
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

java-11-linux:
  image: maven:3.9.5-amazoncorretto-11-debian
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

java-17-linux:
  image: maven:3.9.5-amazoncorretto-17-debian
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

java-21-linux:
  image: maven:3.9.5-amazoncorretto-21-debian
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
