variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"


stages:
  - test-linux
  - test-windows


default:
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml


# ------ Linux ------

# install required packages, use another user but root (so unit tests about not having permissions work fine)- this to assure everything works fine
.entry_point: &entry_point
  - bash
  - -c
  - apt-get update && apt-get install -y libfontconfig1 && useradd -m testuser && exec su testuser -c bash

linux-java-11:
  image: 
    name: maven:3.9.5-amazoncorretto-11-debian
    entrypoint: *entry_point
  stage: test-linux
  script: 
    - mvn $MAVEN_CLI_OPTS test
  when: always

linux-java-17:
  image: 
    name: maven:3.9.5-amazoncorretto-17-debian
    entrypoint: *entry_point
  stage: test-linux
  script: 
    - mvn $MAVEN_CLI_OPTS test
  when: always

linux-java-21:
  image: 
    name: maven:3.9.5-amazoncorretto-21-debian
    entrypoint: *entry_point
  stage: test-linux
  script: 
    - mvn $MAVEN_CLI_OPTS test
  when: always

# ------ Windows ------

# windows-java-21:
#   image:
#     name: amazoncorretto-11-windowsservercore
#   stage: test-windows
#   script:
#     - mvn $MAVEN_CLI_OPTS test
#   when: always
